name: Commits
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify commits
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Verify commit format (only PR commits)
        uses: cocogitto/cocogitto-action@v4
        with:
          command: check --from-ref origin/main

